spring.application.name=BierNotificatieBackend

spring.datasource.url=jdbc:postgresql://localhost:5434/Biernotificatie
spring.datasource.username=postgres
spring.datasource.password=Biernotificatie2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.docker.compose.enabled=false